---
- hosts: all
  remote_user: root

  roles:
    - kubelab

#- hosts: master
#  remote_user: root
#
#  tasks:
#  - name: ensure apache is at the latest version
#    yum:
#      name: httpd
#      state: latest
#  - name: write the apache config file
#    template:
#      src: /srv/httpd.j2
#      dest: /etc/httpd.conf

#- hosts: minions
#  remote_user: root
#
#  tasks:
#  - name: ensure postgresql is at the latest version
#    yum:
#      name: postgresql
#      state: latest
#  - name: ensure that postgresql is started
#    service:
#      name: postgresql
#      state: started
