- name: Create configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
    - /etc/consul.d
    - /etc/consul.d/server
    - /etc/consul.d/client
    - /etc/consul.d/ssl
    - /var/consul

- name: Check if Consul is already installed
  stat: path=/usr/local/bin/consul
  register: file_exists

- name: Download and install Consul binary
  unarchive:
    src: https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not file_exists.stat.exists

- name: Copy Consul server config file
  template:
    src: etc/consul.d/server/config.json.tpl
    dest: /etc/consul.d/server/config.json
    owner: root
    group: root
    mode: "0644"

- name: Copy systemd unit file
  copy:
    src: "etc/systemd/system/consul.service"
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: "0644"

- name: Enable service
  systemd:
    name: consul
    enabled: yes
    daemon_reload: yes

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - 8300/tcp
    - 8301/tcp
    - 8301/udp
    - 8302/tcp
    - 8302/udp
    - 8400/tcp
    - 8500/tcp

- name: Disable NetworkManager DNS setting
  copy:
    src: "etc/NetworkManager/NetworkManager.conf"
    dest: "/etc/NetworkManager/NetworkManager.conf"
    owner: root
    group: root
    mode: "0644"

- name: Restart NetworkManager
  service:
    name: NetworkManager
    state: restarted

- name: Update resolv.conf to use Consul
  copy:
    src: "etc/resolv.conf"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: "0644"
